A patch from Ankush Upadhyay attached by Ratnesh Upadhyay with analysis comments from Swapnil Shah for "Require Inventory of Marketing Package Product can't be shipped" https://issues.apache.org/jira/browse/OFBIZ-817 reported by Daniel Kunkel
Setting Require Inventory for a Marketing Product and (or ???) its Marketing Component causes the shiping system to fail. The shipping system reports nothing is ready to ship, ( [0 + 0 = 0] < 1 ).

---- exception report ----------------------------------------------------------
[TransactionUtil.setRollbackOnly] Calling transaction setRollbackOnly; this stack trace shows where this is happening:
Exception: java.lang.Exception

Message: Error in simple-method [Quick ships an entire order from multiple facilities [file:/wrk/ofbiz/ofbiz/applications/
product/script/org/ofbiz/shipment/shipment/ShipmentServices.xml#quickShipEntireOrder]]: ; [Warning: no shipments created;
could not find anything ready and needing to be shipped.]

---- stack trace ---------------------------------------------------------------

java.lang.Exception: Error in simple-method [Quick ships an entire order from multiple facilities [file:/wrk/ofbiz/ofbiz/
applications/product/script/org/ofbiz/shipment/shipment/ShipmentServices.xml#quickShipEntireOrder]]: ; [Warning: no shipments
created; could not find anything ready and needing to be shipped.]

Swapnil Shah
As per further testing over trunk, it is found that setting requireInventory=Y over any marketing package type product means that for component products as well it would get honored even if its not set as Y for each or any of the components. 
In other words say,
* The flag is as set as Y for a marketing package type product A and it has ATP/QOH=15/15
* Product A has two component B & C as finished good and each having ATP/QOH = 8/8 and requireInventory is not set as Y for any of the components.
*  If sales order is attempted to be placed for A with ordered qty = 10 then system won't allow it to be placed because component B & C don't have sufficient ATP (irrespective of fact that none of them have requireInventory=Y)
Expected behavior in above case should be to allow user to place the order for Product A as it has sufficient ATP=15 to fulfill the ordered qty=10. If the ordered qty happens to exceed 15 then only it should prevent ordering based on requireInventory=Y

Ideally we shouldn't use the MARKETING_PKG product types as its a parent product type for product types MARKETING_PKG_AUTO, MARKETING_PKG_PICK. Thus we have changed the logic in "getMktgPackagesAvailable" service to handle product types MARKETING_PKG_AUTO, MARKETING_PKG_PICK to handle the reported issues more gracefully. Following are the changes we have done in the service vis-a-vis RequireInventory=Y setting for Package and/or its components. Now at the time of add to cart :
# if product type is MARKETING_PKG_AUTO then system will check it's own ATP instead of checking it's component ATP to allow or prevent placing order for package product..
# If product type is MARKETING_PKG_PICK then system will check it's component ATP to allow or prevent placing order for package product.

jleroux:
I agree with Swapnil,, since we can receive inventories of  MARKETING_PKG_AUTO, without regard to their components availability, I see no reasons why we could not ship them. 
BTW I tried the same with MARKETING_PKG_PICK and it works as expected: you need to have the components at hand to ship them even if you tried to receive an inventory before. Since they need to be picked this makes sense.

While at it I fixed a related French label, so it will be backported as well...

git-svn-id: https://svn.apache.org/repos/asf/ofbiz/trunk@1714410 13f79535-47bb-0310-9956-ffa450edef68