No functional change, temporary weird compile error workaround
There is an issue with commit r1507200. It does not compile. 
I wonder though why Buildbot did not detect it and also why my IDE (Eclipse) does not detect it and also why this fails, because the same scheme is successfully used elsewhere.

The demo compilers (1.6.26, mine is 1.6.22, ) say:

classes:
  [javac16] Compiling 11 source files to /home/ofbiz/trunk/applications/party/build/classes
  [javac16] /home/ofbiz/trunk/applications/party/src/org/ofbiz/party/party/PartyServices.java:2097: incompatible types
  [javac16] found   : java.util.Map<java.lang.String,org.ofbiz.entity.GenericValue>
  [javac16] required: java.util.Map<java.lang.String,java.lang.Object>
  [javac16]                     Map<String, Object> postalAddress = UtilMisc.toMap("userLogin", userLogin);
  [javac16]                                                                       ^
  [javac16] /home/ofbiz/trunk/applications/party/src/org/ofbiz/party/party/PartyServices.java:2117: incompatible types
  [javac16] found   : java.util.Map<java.lang.String,org.ofbiz.entity.GenericValue>
  [javac16] required: java.util.Map<java.lang.String,java.lang.Object>
  [javac16]                     Map<String, Object> telecomNumber = UtilMisc.toMap("userLogin", userLogin);
  [javac16]                                                                       ^
  [javac16] 2 errors


Of course replacing by
    java.util.Map<java.lang.String,java.lang.Object> postalAddress = UtilMisc.toMap("userLogin", userLogin);
as the compilers suggest does not help. I temporarily replaced by

Map<String, Object> postalAddress = new HashMap<String, Object>();
postalAddress.put("userLogin", userLogin);

Unrelated: I set my IDE to automatically clean imports...


git-svn-id: https://svn.apache.org/repos/asf/ofbiz/trunk@1507596 13f79535-47bb-0310-9956-ffa450edef68